server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: ms-prices
          uri: lb://ms-prices
          predicates:
            - Path=/prices/**
        - id: ms-repairs
          uri: lb://ms-repairs
          predicates:
            - Path=/repairs/**
        - id: ms-reports
          uri: lb://ms-reports
          predicates:
            - Path=/reports/**
        - id: ms-vehicles
          uri: lb://ms-vehicles
          predicates:
            - Path=/vehicles/**