server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:mysql://${}:3306/prices-db
    username: root
    password: mysql2024$
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}