server:
  port: 8093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reports-db
    username: root
    password: mysql2024$
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka