apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-reports-deployment
  labels:
    app: ms-reports-deployment
spec:
  selector:
    matchLabels:
      app: ms-reports-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-reports-deployment
    spec:
      containers:
        - name: ms-reports
          image: josemaring/ms-reports
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            # Config-map
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_REPORTS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_REPORTS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_REPORTS
            # Secrets
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_REPORTS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_REPORTS