apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-repairs-deployment
  labels:
    app: ms-repairs-deployment
spec:
  selector:
    matchLabels:
      app: ms-repairs-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-repairs-deployment
    spec:
      containers:
        - name: ms-repairs
          image: josemaring/ms-repairs
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            # Config-map
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_REPAIRS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_REPAIRS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_REPAIRS
            # Secrets
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_REPAIRS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_REPAIRS