apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/reports-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-db-pvc
  labels:
    app: mysql
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-db-deployment
  labels:
    app: reports-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: reports-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reports-db-deployment
        tier: database
    spec:
      containers:
        - name: reports-db
          image: mysql
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_REPORTS
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: reports-db-data
      volumes:
        - name: reports-db-data
          persistentVolumeClaim:
            claimName: reports-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: reports-db-service
  labels:
    app: reports-db-service
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: reports-db-deployment
    tier: database
  type: LoadBalancer